<?php

  class Formulario{

    public function equipoAlta($alumno){

    echo '<div id="crearIntegrantes" class="container"><div class="row justify-content-md-center"><div class="col-md-8 col-sm-12 align-items-center"><form  id="equipo" method="post"  action="aplicarMovimiento.php"><input value="'.$alumno.'" name="fechaGrupo" type="text" class="form-control" style="display:none"><div class="form-group row"><label for="numProyecto" class="col-md-4 my-2 col-form-label">N° de Equipo</label><div class="col-md-8 my-2"><input type="number" class="form-control" min="1" max="8" step="1" name="numProyecto" id="numProyecto" required></div></div><div class="form-group row"><label for="hora" class="col-md-4 my-2 col-form-label">Hora</label><div class="col-md-8 my-2"><input type="time" class="form-control" min="07:00" max="19:00" step="600" name="hora" id="hora" required></div></div><div class="form-group row"><label for="nombreProyecto" class="col-md-4 my-2 col-form-label">Nombre del Equipo</label><div class="col-md-8 my-2"><input type="text" maxlength="15" class="form-control" name="nombreProyecto" id="nombreProyecto" required></div></div><div class="form-group row"><label for="problematica" class="col-md-4 my-2 col-form-label">Problemática</label><div class="col-md-8 my-2"><input value="'.$_SESSION["nombreUsu"].'" name="grado" type="text" class="form-control" style="display:none"><input  type="text" id="problematica" maxlength="30" class="form-control" name="problematica"  required></div></div><div class="form-group row"><label  for="add_cancion()" class="col-md-4 my-4 col-form-label">Integrantes</label><div class="col-md-8 my-4"><button type="button" class="btn btn-utj" id="add_cancion()" onClick="addCancion();"><i class="fas fa-plus"></i> Agregar</button></div></div><div id="inte"></div><button type="submit" onClick="validar();" name="altaEquipo" class="btn btn-primary my-4 mb-2"><i class="text-white  fas fa-save"></i>  Guardar</button></form></div></div></div>';

  }
    public function calificacionDeEquipo($cont){
      $usuario = $_SESSION['nombreUsu'];
      echo '<form  name="cal'.$cont.'" method="post" action="aplicarMovimiento.php?contG='.$cont.'"><input value="'.$usuario.'" name="codigoProfesor" type="text" class="form-control" style="display:none"><div class="form-row"><div class="col-sm-4 col-md-3 my-3"><label for="puntu">Puntualidad</label><input type="number" min="7" max="10" step="0.5" class="form-control" id="puntu"  name="puntu" required></div><div class="col-sm-4 col-md-3 my-3"><label for="prePer">Presentación Personal</label><input type="number" min="7" max="10" step="0.5" class="form-control" id="prePer" name="prePer" required></div><div class="col-sm-4 col-md-3 my-3"><label for="expOral">Expresión Oral</label><input type="number" min="7" max="10" step="0.5" class="form-control" id="expOral" name="expOral" required></div><div class="col-sm-4 col-md-3 my-3"><label for="orgEquipo">Organización de Equipo</label><input type="number"  min="7" max="10" step="0.5" class="form-control" id="orgEquipo" name="orgEquipo" required></div></div><div class="form-row"><div class="col-sm-4 col-md-3 my-3"><label for="apVisual">Apoyos Visuales</label><input type="number"  min="7" max="10" step="0.5" class="form-control" id="apVisual"  name="apVisual" ></div><div class="col-sm-4 col-md-3 my-3"><label for="conTema">Contenido Temático</label><input  type="number" min="7" max="10" step="0.5" class="form-control" id="conTema"  name="conTema" ></div><div class="col-sm-4 col-md-3 my-3"><label for="domTem">Dominio del Tema</label><input type="number"  min="7" max="10" step="0.5" class="form-control" id="domTem" name="domTem" required></div></div><div class="form-row"><div class="col-sm-6 col-md-6"><label for="recomed">Recomendaciones</label><textarea class="form-control" name="recomed" id="recomed" maxlength="65" rows="3" required></textarea></div><div class="offset-sm-1 col-sm-4 offset-md-1 col-md-3 pt-5"><button type="submit" name="altaCal" class="btn btn-primary btn-lg"><i class="text-white  fas fa-save"></i> Guardar</button></div></div>';
    }

  }

?>
